### ISSUE TITLE
OGPの設定

### ISSUE THREAD

**Issue by addtobasic** [Yuta1004/SysDC#278]
## 概要
OGP画像が設定されていないのが少しに気なったのでissueを立てることで設定をしろという圧をかけていく.

## やること
- OGP画像の作成 (1200 * 600が好ましい).
- OGPの設定 ([react-helmet](https://www.npmjs.com/package/react-helmet)というやつがいいかもです).
- 設定後に反映されているかの確認 ([このサイト](https://rakko.tools/tools/9/) がおすすめです).

**Comment by Yuta1004** [comment]
マージしました！（ #281）
一部上手く動かない箇所があったので修正しました :bowing_man: 

- 動的OGP→静的OGP
- 画像ファイル名の変更
